### ISSUE TITLE
Wario Land 2: Graphical corruption

### ISSUE THREAD

**Issue by jduckett95** [jduckett95/infinest-pocket-patches#2]
I noticed that the sprites in Wario Land 2 are messed up in the first boss fight. (Snake) Was able to complete it but I’m reluctant to play further if there’s a game breaking bug to be found.

(From: VerusVerenus on Reddit)

**Comment by Infinest** [comment]
![image](https://user-images.githubusercontent.com/7109154/147842470-d1c8bcf5-395f-47b2-bceb-6e54f7145afd.png)
I've just tested this myself and had no visual or gameplay glitches. If i had to guess i'd say the person who posted about the issue either had the original version of the patch or an incorrect base ROM
