### ISSUE TITLE
Wario Land II: Missing cutscenes in ending and credits

### ISSUE THREAD

**Issue by Vidnez** [jduckett95/infinest-pocket-patches#4]
Some cutscenes are missing in the ending and the credits.

**Comment by Infinest** [comment]
Thanks for reporting the issue. This one was a bit tricky but it should be fixed now.
@jduckett95 here's the updated patch.

[Wario Land II Analogue Pocket patch 1.3.zip](https://github.com/jduckett95/infinest-pocket-patches/files/7919174/Wario.Land.II.Analogue.Pocket.patch.1.3.zip)
